In [1]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv(r"C:\Users\omgai\Downloads\spam (1).csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [12]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [14]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [20]:
X_train.shape

(4457,)

In [24]:
X_test.shape

(1115,)

In [26]:
type(X_train)

pandas.core.series.Series

In [28]:
X_train[:4]

3747               I'm not. She lip synced with shangela.
5459    If you hear a loud scream in about &lt;#&gt; m...
4894                               Send me the new number
1327                      Sorry, was in the bathroom, sup
Name: Message, dtype: object

In [32]:
type(y_train)

pandas.core.series.Series

In [34]:
y_train[:4]

3747    0
5459    0
4894    0
1327    0
Name: spam, dtype: int64

In [36]:
type(X_train.values)

numpy.ndarray

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7750 sparse matrix of type '<class 'numpy.int64'>'
	with 59384 stored elements in Compressed Sparse Row format>

In [40]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
X_train_cv.shape

(4457, 7750)

In [44]:
v.get_feature_names_out()[1771]

'charges'

In [46]:
v.vocabulary_

{'not': 4853,
 'she': 6112,
 'lip': 4177,
 'synced': 6698,
 'with': 7558,
 'shangela': 6102,
 'if': 3651,
 'you': 7711,
 'hear': 3430,
 'loud': 4256,
 'scream': 5991,
 'in': 3688,
 'about': 772,
 'lt': 4282,
 'gt': 3308,
 'minutes': 4527,
 'its': 3812,
 'cause': 1722,
 'my': 4687,
 'gyno': 3337,
 'will': 7528,
 'be': 1299,
 'shoving': 6166,
 'things': 6868,
 'up': 7197,
 'me': 4435,
 'that': 6832,
 'don': 2443,
 'belong': 1343,
 'send': 6045,
 'the': 6836,
 'new': 4782,
 'number': 4882,
 'sorry': 6369,
 'was': 7398,
 'bathroom': 1277,
 'sup': 6640,
 'sir': 6223,
 'need': 4749,
 'axis': 1201,
 'bank': 1247,
 'account': 800,
 'no': 4821,
 'and': 984,
 'address': 832,
 'ey': 2773,
 'calm': 1658,
 'downon': 2467,
 'theacusations': 6838,
 'itxt': 3815,
 'cos': 2055,
 'iwana': 3819,
 'know': 4002,
 'wotu': 7618,
 'doin': 2434,
 'at': 1144,
 'thew': 6861,
 'end': 2623,
 'haventcn': 3413,
 'ages': 885,
 'ring': 5820,
 'ur': 7214,
 'up4': 7198,
 'nething': 4771,
 'sat': 5945,
 'love': 4261,
 'x

In [48]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
np.where(X_train_np[0]!=0)

(array([4177, 4853, 6102, 6112, 6698, 7558], dtype=int64),)

In [56]:
X_train_np[0][7558]

1

In [58]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [60]:
X_test_cv = v.transform(X_test)

In [62]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       956
           1       0.97      0.91      0.94       159

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [64]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [66]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [68]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       956
           1       0.97      0.91      0.94       159

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

